name: Hyperfocus CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  client-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Clean install dependencies
      run: cd hf-client && npm ci
    - name: Run linting
      run: cd hf-client && npm run lint
  server-test-lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Clean install dependencies
      run: cd hf-server && npm ci
    - name: Run tests
      run: cd hf-server && npm run test-standalone
    - name: Run linting
      run: cd hf-server && npm run lint